export const enum ROUTES_ENUM {
  Dashboard = "dashboard",
  Info = "info",
  Muppet = "muppet",
  MuppetForm = "muppet-form",
  MuppetStats = "muppet-stats",
  MuppetRandom = "muppet-random",
  Bookmarks = "bookmarks",
  BookmarkOverview = "bookmark-overview",
  BookmarkForm = "bookmark-form",
  Profile = "profile",
  Stage = "stage",
  Links = "links",
  Monitor = "monitor",
  SuperlativeScavenger = "superlative-scavenger",
  Phasmaphobia = "phasmaphobia",
  Admin = "admin",
  Login = "login",
}
