export const enum ROUTES_ENUM {
  Dashboard = "",
  Info = "info",
  Muppet = "muppet",
  MuppetForm = "muppet-form",
  MuppetStats = "muppet-stats",
  MuppetRandom = "muppet-random",
  Bookmarks = "bookmarks",
  BookmarkOverview = "bookmark-overview",
  BookmarkForm = "bookmark-form",
  Profile = "profile",
  Stage = "stage",
  Links = "links",
  Monitor = "monitor",
  MissingWord = "missing-word",
  SuperlativeScavenger = "superlative-scavenger",
  TunnelGoonsGallery = "tunnel-goons-gallery",
  TunnelGoonsGenerator = "tunnel-goons-generator",
  TunnelGoons = "tunnel-goons",
  Admin = "admin",
  Login = "login",
  MarkdownViewer = "view",
}
